### ISSUE TITLE
Crash script while autoloading after reboot

### ISSUE THREAD

**Issue by Yoda49** [hellogrojo/pi-utils#3]
Script crash with log:

```
/home/antio/smarthome/node_modules/pi-utils/lib/wifi.js:42
		return new Promise((resolve, reject) => {
		                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/antio/smarthome/node_modules/pi-utils/index.js:2:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
error: Forever detected script exited with code: 8
```

Raspberry pi 3, node 7.7.4

**Comment by aaronhastings** [comment]
This is ES6 syntax, so if you are getting an error at this point, it would imply the version of node that is running at boot is not 7.7.4, but an older version.  So this is most likely a system configuration issue.  Please feel free to reopen if you feel this is not the case.
